// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminNavigationMain: typeof import('./../components/Admin/Navigation/Main.vue')['default']
    AdminNavigationSidebar: typeof import('./../components/Admin/Navigation/Sidebar.vue')['default']
    ConstructButton: typeof import('./../components/Construct/Button.vue')['default']
    ConstructForm: typeof import('./../components/Construct/Form.vue')['default']
    ConstructInput: typeof import('./../components/Construct/Input.vue')['default']
    ConstructLayout: typeof import('./../components/Construct/Layout.vue')['default']
    ConstructLink: typeof import('./../components/Construct/Link.vue')['default']
    ConstructMenuButton: typeof import('./../components/Construct/MenuButton.vue')['default']
    ConstructPage: typeof import('./../components/Construct/Page.vue')['default']
    ConstructScrollNotifier: typeof import('./../components/Construct/ScrollNotifier.vue')['default']
    ConstructSelect: typeof import('./../components/Construct/Select.vue')['default']
    ConstructTextArea: typeof import('./../components/Construct/TextArea.vue')['default']
    ConstructTitle: typeof import('./../components/Construct/Title.vue')['default']
    NavigationMain: typeof import('./../components/Navigation/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./../components/User/Avatar.vue')['default']
    UserDisplayName: typeof import('./../components/User/DisplayName.vue')['default']
    UserEmail: typeof import('./../components/User/Email.vue')['default']
    UserName: typeof import('./../components/User/Name.vue')['default']
    UserProvider: typeof import('./../components/User/Provider.vue')['default']
    UserRoleDisplayName: typeof import('./../components/User/Role/DisplayName.vue')['default']
    UserRoleName: typeof import('./../components/User/Role/Name.vue')['default']
    UserRoleProvider: typeof import('./../components/User/Role/Provider.vue')['default']
  }
}
