// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminNavigationSidebar: typeof import('./../components/Admin/Navigation/Sidebar.vue')['default']
    ConstructButton: typeof import('./../components/Construct/Button.vue')['default']
    ConstructInput: typeof import('./../components/Construct/Input.vue')['default']
    ConstructLayout: typeof import('./../components/Construct/Layout.vue')['default']
    ConstructLink: typeof import('./../components/Construct/Link.vue')['default']
    ConstructPage: typeof import('./../components/Construct/Page.vue')['default']
    ConstructTitle: typeof import('./../components/Construct/Title.vue')['default']
    NavigationMain: typeof import('./../components/Navigation/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
